name: Lint

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install Dependencies
        run: |
          yarn install
      - name: yarn run lint
        run: |
          yarn run lint
